name: ci_git

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        #pip install pylint
        pip install flake8 pytest
        pip install -r requirements.txt
    - name: Analysing the code with flake8
      run: |
        #pylint $(git ls-files '*.py')
        flake8 .
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Test code with pytest
      run: |
        pytest tests/extractor/test_extract.py
        pytest tests/code_parser/test_tree_sitter_parser.py
        pytest tests/lang_parser/test_enry_parser.py
        python3 -m pytest test_github_api.py --key ${{ secrets.GITHUB_TOKEN }}